import { BooksResponse } from "@/components/books/BookGrid/BookGrid.types";

export const mockBooksResponse: BooksResponse = {
    pageNumber: 1,
    pageSize: 10,
    totalNumberOfPages: 1,
    books: [
        {
            bookId: "1",
            title: "Pashchima Ghattada Tappalinalli",
            shortDescription: "A thrilling journey through the dense and mysterious forests of the Western Ghats.",
            label: "New",
            price: { value: 450, currency: "INR", uom: "EA" },
            inventory: { quantity: 40, active: true },
            primaryImageUrl: "/images/books/book1.jpg",
            reviews: { totalNumberOfReviews: 124, maxRating: 5, avgRatingReceived: 4.5 },
            offers: [],
        },
        {
            bookId: "2",
            title: "Jenu Kallina Rahasya Kanive",
            shortDescription: "A suspense-filled tale unraveling secrets hidden in a rocky valley.",
            price: { value: 550, currency: "INR", uom: "EA" },
            inventory: { quantity: 25, active: true },
            primaryImageUrl: "/images/books/book2.jpg",
            reviews: { totalNumberOfReviews: 89, maxRating: 5, avgRatingReceived: 4.2 },
            offers: [
                {
                    id: "offer-2",
                    title: "10% off",
                    description: "10% discount on Jenu Kallina Rahasya Kanive",
                    offerPrice: {
                        value: 550,
                        discountValue: 10,
                        discountType: "percentage",
                        discountAmount: 55,
                        currency: "INR",
                        uom: "EA",
                        valueAfterDiscount: 495,
                    },
                },
            ],
        },
        {
            bookId: "3",
            title: "Hudugata Hudukata",
            shortDescription: "An adventurous search that blends innocence, courage, and curiosity.",
            label: "Bestseller",
            price: { value: 480, currency: "INR", uom: "EA" },
            inventory: { quantity: 60, active: true },
            primaryImageUrl: "/images/books/book3.jpg",
            reviews: { totalNumberOfReviews: 256, maxRating: 5, avgRatingReceived: 4.8 },
            offers: [],
        },
        {
            bookId: "4",
            title: "Mungarina Kere",
            shortDescription: "A rain-soaked village tale where nature and mystery intertwine.",
            price: { value: 520, currency: "INR", uom: "EA" },
            inventory: { quantity: 35, active: true },
            primaryImageUrl: "/images/books/book4.jpg",
            reviews: { totalNumberOfReviews: 67, maxRating: 5, avgRatingReceived: 4.0 },
            offers: [],
        },
        {
            bookId: "5",
            title: "Ondu Aaneya Sutta",
            shortDescription: "An engaging story where a single incident changes many lives.",
            label: "Trending",
            price: { value: 490, currency: "INR", uom: "EA" },
            inventory: { quantity: 45, active: true },
            primaryImageUrl: "/images/books/book5.jpg",
            reviews: { totalNumberOfReviews: 178, maxRating: 5, avgRatingReceived: 4.6 },
            offers: [
                {
                    id: "offer-5",
                    title: "15% off",
                    description: "15% discount on Ondu Aaneya Sutta",
                    offerPrice: {
                        value: 490,
                        discountValue: 15,
                        discountType: "percentage",
                        discountAmount: 73.5,
                        currency: "INR",
                        uom: "EA",
                        valueAfterDiscount: 416.5,
                    },
                },
            ],
        },
        {
            bookId: "6",
            title: "Kaadu Tilisida Satyagalu",
            shortDescription: "Truths revealed by the forest through silence and survival.",
            label: "Featured",
            price: { value: 600, currency: "INR", uom: "EA" },
            inventory: { quantity: 30, active: true },
            primaryImageUrl: "/images/books/book6.jpg",
            reviews: { totalNumberOfReviews: 145, maxRating: 5, avgRatingReceived: 4.7 },
            offers: [],
        },
        {
            bookId: "7",
            title: "Anaatha Hakkiya Koogu",
            shortDescription: "A moving story of loss, resilience, and the call of the wild.",
            price: { value: 470, currency: "INR", uom: "EA" },
            inventory: { quantity: 50, active: true },
            primaryImageUrl: "/images/books/book7.jpg",
            reviews: { totalNumberOfReviews: 92, maxRating: 5, avgRatingReceived: 4.3 },
            offers: [],
        },
        {
            bookId: "8",
            title: "Girikandara Estate",
            shortDescription: "An atmospheric tale set in a mist-covered Malenadu estate.",
            price: { value: 530, currency: "INR", uom: "EA" },
            inventory: { quantity: 28, active: true },
            primaryImageUrl: "/images/books/book8.jpg",
            reviews: { totalNumberOfReviews: 103, maxRating: 5, avgRatingReceived: 4.4 },
            offers: [],
        },
    ],
};
