import { BooksResponse } from "@/components/books/BookGrid/BookGrid.types";

export const mockBooksResponse: BooksResponse = {
    pageNumber: 1,
    pageSize: 10,
    totalNumberOfPages: 1,
    books: [
        {
            bookId: "1",
            title: "The Journey of Words",
            shortDescription: "A profound exploration of language and its transformative power.",
            label: "New",
            price: { value: 450, currency: "INR", uom: "EA" },
            inventory: { quantity: 40, active: true },
            primaryImageUrl: "/images/books/book-1.jpg",
            reviews: { totalNumberOfReviews: 124, maxRating: 5, avgRatingReceived: 4.5 },
            offers: [],
        },
        {
            bookId: "2",
            title: "Tales from the Heartland",
            shortDescription: "Timeless tales capturing the essence of rural life.",
            price: { value: 550, currency: "INR", uom: "EA" },
            inventory: { quantity: 25, active: true },
            primaryImageUrl: "/images/books/book-2.jpg",
            reviews: { totalNumberOfReviews: 89, maxRating: 5, avgRatingReceived: 4.2 },
            offers: [
                {
                    id: "offer-2",
                    title: "10% off",
                    description: "10% discount on Tales from the Heartland",
                    offerPrice: {
                        value: 550,
                        discountValue: 10,
                        discountType: "percentage",
                        discountAmount: 55,
                        currency: "INR",
                        uom: "EA",
                        valueAfterDiscount: 495,
                    },
                },
            ],
        },
        {
            bookId: "3",
            title: "Echoes of Tradition",
            shortDescription: "Bridging the past and present through cultural narratives.",
            label: "Bestseller",
            price: { value: 480, currency: "INR", uom: "EA" },
            inventory: { quantity: 60, active: true },
            primaryImageUrl: "/images/books/book-3.jpg",
            reviews: { totalNumberOfReviews: 256, maxRating: 5, avgRatingReceived: 4.8 },
            offers: [],
        },
        {
            bookId: "4",
            title: "Voices of the Past",
            shortDescription: "Stories and teachings from ancestors that remain relevant today.",
            price: { value: 520, currency: "INR", uom: "EA" },
            inventory: { quantity: 35, active: true },
            primaryImageUrl: "/images/books/book-4.jpg",
            reviews: { totalNumberOfReviews: 67, maxRating: 5, avgRatingReceived: 4.0 },
            offers: [],
        },
        {
            bookId: "5",
            title: "Stories of Wisdom",
            shortDescription: "A treasury of wisdom stories illuminating life's deepest truths.",
            label: "Trending",
            price: { value: 490, currency: "INR", uom: "EA" },
            inventory: { quantity: 45, active: true },
            primaryImageUrl: "/images/books/book-5.jpg",
            reviews: { totalNumberOfReviews: 178, maxRating: 5, avgRatingReceived: 4.6 },
            offers: [
                {
                    id: "offer-5",
                    title: "15% off",
                    description: "15% discount on Stories of Wisdom",
                    offerPrice: {
                        value: 490,
                        discountValue: 15,
                        discountType: "percentage",
                        discountAmount: 73.5,
                        currency: "INR",
                        uom: "EA",
                        valueAfterDiscount: 416.5,
                    },
                },
            ],
        },
        {
            bookId: "6",
            title: "The Cultural Tapestry",
            shortDescription: "Exploring the intricate threads of our cultural fabric.",
            label: "Featured",
            price: { value: 600, currency: "INR", uom: "EA" },
            inventory: { quantity: 30, active: true },
            primaryImageUrl: "/images/books/book-6.jpg",
            reviews: { totalNumberOfReviews: 145, maxRating: 5, avgRatingReceived: 4.7 },
            offers: [],
        },
        {
            bookId: "7",
            title: "Legacy of Words",
            shortDescription: "Examining the lasting impact of literature on civilization.",
            price: { value: 470, currency: "INR", uom: "EA" },
            inventory: { quantity: 50, active: true },
            primaryImageUrl: "/images/books/book-7.jpg",
            reviews: { totalNumberOfReviews: 92, maxRating: 5, avgRatingReceived: 4.3 },
            offers: [],
        },
        {
            bookId: "8",
            title: "Timeless Narratives",
            shortDescription: "Narratives that transcend time and speak to universal experiences.",
            price: { value: 530, currency: "INR", uom: "EA" },
            inventory: { quantity: 28, active: true },
            primaryImageUrl: "/images/books/book-8.jpg",
            reviews: { totalNumberOfReviews: 103, maxRating: 5, avgRatingReceived: 4.4 },
            offers: [],
        },
    ],
};
